#!/bin/ksh
# |/ /_ |_| |_\ /
# |\  / | | | \ \
# ~/etc/kshrc : ksh initialisation

# vi mode baby
set -o vi

# prompt
_prompt() {
	if [ $? -ne 0 -a $? -ne 130 ]; then
		printf '\033[31m'
	else
		printf '\033[97m'
	fi

	if [ $(id -u) -ne 0 ]; then
		printf '$'
	else
		printf '#'
	fi

	printf '\033[0m'
}
export PS1='$(_prompt) '

# variables
export VIS_PATH="$HOME/etc/vis"

# alias
alias \!\!='$(fc -l | tail -1 | cut -f 2)'
alias f='finger'
alias h='history -r | less'
alias j='jobs -l'
alias la='ls -a'
alias l='ls -Fhl'
alias ll='ls -AFhl'
alias mv='mv -i'
alias p='ps'
alias rm='rm -i'

# OS specific configuration
if [ $(id -u) -ne 0 ]; then
	case "$(uname -s)" in
		OpenBSD) . $HOME/etc/kshrc.openbsd   ;;
		Linux)   . $HOME/etc/kshrc.alpinewsl ;;
	esac
fi

# setup a tmux session for development
setupdev() {
	tmux new-session -d
	tmux split-window -v
	tmux new-window
	tmux previous-window
	tmux attach-session -d
}

# oopsie
dosa() {
	echo "yum!"
	doas "$@"
}

# make a quick backup of a file 
# usage: bak <file>
bak() {
	cp -vr "$1" "${1}.bak"
}

# generate a quick filename (current date)
fname() {
	echo "`date '+%b.%d-%H%M'`"
}

# make a dir and cd into it
mkcd() {
	if [ $# -eq 1 ]; then 
		eval local path=\$$#
	else
		echo "insufficient arguments given..."
		return 1
	fi
	mkdir -p $@
	cd "$path"
}

# shh...
if [ $(id -u) -ne 0 ]; then
	. ~/.secrets
fi
