#!/bin/ksh
# |/ /_ |_| |_\ /
# |\  / | | | \ \
# ~/etc/kshrc : ksh initialisation

# vi mode baby
set -o vi

# variables
export ETC=${HOME}/etc
export PATH="${HOME}/bin:${HOME}/bin/sym:${PATH}"
export XDG_CONFIG_HOME=${ETC}
export XDG_CACHE_HOME=${HOME}/var

# shortenings
alias f='finger'
alias h='history -r | less'
alias j='jobs -l'
alias p='ps'

# ls
alias ls='ls -F'
alias la='ls -AF'
alias ll='ls -AlFh'
alias l='ls -Fhl'

# mv
alias mv='mv -iv'
alias cp='cp -iv'
alias rm='rm -iv'

# useful aliases
alias \!\!='$(fc -l | tail -1 | cut -f 2)'
alias popd='cd -'

# OS specific configuration
if [ $(id -u) -ne 0 ]; then
	case "$(uname -s)" in
		OpenBSD) . $HOME/etc/kshrc.openbsd ;;
		Linux)   . $HOME/etc/kshrc.wsl     ;;
	esac
fi

# setup a tmux session for "development"
setupdev() {
	tmux new-session -d
	tmux split-window -v
	tmux new-window
	tmux previous-window
	tmux attach-session -d
}

# make a quick backup of a file 
# usage: bak <file>
bak() {
	cp -vr "$1" "${1}.bak"
}

# generate a quick filename (current date)
fname() {
	date '+%F-%H%M'
}
alias fn='fname'

# new blog post
blog() {
	title="${1:-title}"
	date="$(date '+%F')"
	vise "${HOME}/usr/txt/${date}-${title}.md"
}

# make a dir and cd into it
mkcd() {
	if [ $# -lt 1 ]; then 
		echo "insufficient arguments given..."
		return 1
	fi

	eval local path=\$$#

	mkdir $@
	cd "$path"
}

# shh...
if [ $(id -u) -ne 0 ]; then
	. ~/.secrets
fi
