#!/bin/ksh
# |/ /_ |_| |_\ /
# |\  / | | | \ \
# ~/etc/kshrc : ksh initialisation

# vi mode baby
set -o vi

# variables
export VIS_PATH="$HOME/etc/vis"
export PS1="\W\$ "

# alias
alias \!\!='history | tail -1 | cut -f 2'
alias f='finger'
alias h='history -r | less'
alias j='jobs -l'
alias la='ls -a'
alias l='ls -Fhl'
alias ll='ls -AFhl'
alias mv='mv -i'
alias p='ps'
alias rm='rm -i'

# OS specific configuration
case "$(uname -s)" in
	OpenBSD) . $HOME/etc/kshrc.openbsd   ;;
	Linux)   . $HOME/etc/kshrc.alpinewsl ;;
esac

# setup a tmux session for development
setupdev() {
	tmux new-session -d
	tmux split-window -v
	tmux new-window
	tmux previous-window
	tmux attach-session -d
}

# oopsie
dosa() {
	echo "yum!"
	doas "$@"
}

# make a quick backup of a file 
# usage: bak <file>
bak() {
	cp -vr "$1" "${1}.bak"
}

# generate a quick filename (current date)
fname() {
	echo "`date '+%b.%d-%H%M'`"
}

# make a dir and cd into it
mkcd() {
	if [ $# -eq 1 ]; then 
		eval local path=\$$#
	else
		echo "insufficient arguments given..."
		return 1
	fi
	mkdir -p $@
	cd "$path"
}

# shh...
. ~/.secrets
