[common]
xftFont = "JetBrains Mono:style=Regular:size=14"

[cwmrc]
path = "~/etc/cwmrc"

[bar]
#xftFont = "Inconsolata:style=Regular:antialiased=true"
path = "~/etc/bar.conf"
accent = "#ffffff"
background = "#a9aea9"
foreground = "#ffffff"
border = "#E9E9E9"
border_width = "0"
