#!/bin/sh
# \/ /_ /_\ /_ /_ | /\ |\|
# /\  / \_   /  / | \/ | |
# ~/.xsession : loaded on login by xenodm(1)

# merge .Xdefaults
if [ -f ${HOME}/.Xdefaults ]; then
	xrdb -merge ${HOME}/.Xdefaults
fi

# LANG & PATH
export LANG=en_AU.UTF-8
PATH="${HOME}/bin:${HOME}/bin/bsd:${HOME}/bin/sym:${PATH}"

# wallpaper
xsetroot -solid \#edeeef

# bar
status | bar &

# xbanish
xbanish -i shift &

# cursor
xsetroot -cursor_name X_cursor &

# wm
exec cwm -c ${HOME}/etc/cwmrc
